# Generated by Django 3.0.4 on 2020-08-18 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlhandler', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shorturl',
            name='short_query',
            field=models.CharField(max_length=60),
        ),
    ]
